### ISSUE TITLE
persistent shared data directory not working after deleting container

### ISSUE THREAD

**Issue by rajalokan** [dockerfile/rabbitmq#22]
I've deployed a rabbitmq container using `docker-compose` which works absolutely fine. But when I stop the service, remove the container and then restart again I don't see rabbitmq data persistent. 

Here is how to reproduce it:
# docker-compose.yml:

```
rabbitmq:
  image: dockerfile/rabbitmq
  container_name: rabbitmq
  volumes:
    - /srv/docker/osod/rabbitmq:/data/mnesia
  ports:
    - "5672:5672"
    - "15672:15672"
```
# Dockerfile

Same as https://github.com/dockerfile/rabbitmq/blob/master/Dockerfile
# Steps:

```
docker-compose up -d rabbitmq
docker exec -it rabbitmq rabbitmqctl list_users
    Listing users ...
    guest   [administrator]
docker exec -it rabbitmq rabbitmqctl add_user user1 123
    Creating user "user1" ...
docker exec -it rabbitmq rabbitmqctl set_permissions user1 ".*" ".*" ".*"
    Setting permissions for user "user1" in vhost "/" ...
docker exec -it rabbitmq rabbitmqctl list_users
    Listing users ...
        user1   []
        guest   [administrator]
```

Now when I stop, remove and start container again

```
docker-compose stop
docker rm $(docker ps -aq --filter "status=exited")
docker-compose up -d rabbitmq
docker exec -it rabbitmq rabbitmqctl list_users
    Listing users ...
    guest   [administrator]
```

As we can see `user1` is missing. Can you please suggest where I'm doing wrong. Doing same with mysql persisted data works though.
